language: minimal
notifications:
  email:
    on_success: change
    on_failure: change
addons:
  apt:
    packages:
      - docker-ce
      - qemu-user-static
stages:
  - "Prepare"
  - name: "Deploy"
    if: branch = master AND repo = smockle/ddns53
jobs:
  include:
    # PREPARE
    - stage: "Prepare"
      name: amd64
      script:
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        - docker build --build-arg ARCH="amd64" --build-arg ONTEST="ONTEST" -t smockle/ddns53:amd64 -f Dockerfile .
        - docker run --rm -it smockle/ddns53:amd64 sh -c /usr/local/bin/ddns53.test.sh
      after_success:
        - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_REPO_SLUG" == "smockle/ddns53" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; fi
        - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_REPO_SLUG" == "smockle/ddns53" ]; then docker push smockle/ddns53:amd64; fi
    - #
      name: arm
      script:
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        - docker build --build-arg ARCH="armhf" --build-arg ONTEST="ONTEST" -t smockle/ddns53:arm -f Dockerfile .
        - docker run --rm -it smockle/ddns53:arm sh -c /usr/local/bin/ddns53.test.sh
      after_success:
        - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_REPO_SLUG" == "smockle/ddns53" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; fi
        - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_REPO_SLUG" == "smockle/ddns53" ]; then docker push smockle/ddns53:arm; fi
    # DEPLOY
    - stage: "Deploy"
      name: latest
      script: skip
      before_deploy: docker image ls && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      deploy:
        - provider: script
          skip_cleanup: true
          script: docker manifest create smockle/ddns53:latest smockle/ddns53:amd64 smockle/ddns53:arm && docker manifest annotate smockle/ddns53:latest smockle/ddns53:amd64 --os linux --arch amd64 && docker manifest annotate smockle/ddns53:latest smockle/ddns53:arm --os linux --arch arm && docker manifest push smockle/ddns53:latest
          on:
            branch: master
            repo: smockle/ddns53
            tags: false
